name: TerrainExporter
version: 1.0
main: net.oldschoolminecraft.te.TerrainExporter
author: ChatGPT
commands:
  exportterrain:
    description: Export terrain surface data
  savechunk:
    description: Export the current chunk (or a radius)
  import:
    description: Import a chunk